USE [master]
GO
/****** Object:  Database [OnMuhasebe]    Script Date: 29.01.2021 16:08:20 ******/
CREATE DATABASE [OnMuhasebe]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'OnMuhasebe', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\OMDB2_Primary.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'OnMuhasebe_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\OMDB2_Primary.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [OnMuhasebe] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [OnMuhasebe].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [OnMuhasebe] SET ANSI_NULL_DEFAULT ON 
GO
ALTER DATABASE [OnMuhasebe] SET ANSI_NULLS ON 
GO
ALTER DATABASE [OnMuhasebe] SET ANSI_PADDING ON 
GO
ALTER DATABASE [OnMuhasebe] SET ANSI_WARNINGS ON 
GO
ALTER DATABASE [OnMuhasebe] SET ARITHABORT ON 
GO
ALTER DATABASE [OnMuhasebe] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [OnMuhasebe] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [OnMuhasebe] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [OnMuhasebe] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [OnMuhasebe] SET CURSOR_DEFAULT  LOCAL 
GO
ALTER DATABASE [OnMuhasebe] SET CONCAT_NULL_YIELDS_NULL ON 
GO
ALTER DATABASE [OnMuhasebe] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [OnMuhasebe] SET QUOTED_IDENTIFIER ON 
GO
ALTER DATABASE [OnMuhasebe] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [OnMuhasebe] SET  DISABLE_BROKER 
GO
ALTER DATABASE [OnMuhasebe] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [OnMuhasebe] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [OnMuhasebe] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [OnMuhasebe] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [OnMuhasebe] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [OnMuhasebe] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [OnMuhasebe] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [OnMuhasebe] SET RECOVERY FULL 
GO
ALTER DATABASE [OnMuhasebe] SET  MULTI_USER 
GO
ALTER DATABASE [OnMuhasebe] SET PAGE_VERIFY NONE  
GO
ALTER DATABASE [OnMuhasebe] SET DB_CHAINING OFF 
GO
ALTER DATABASE [OnMuhasebe] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [OnMuhasebe] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [OnMuhasebe] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [OnMuhasebe] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [OnMuhasebe] SET QUERY_STORE = OFF
GO
USE [OnMuhasebe]
GO
/****** Object:  Table [dbo].[AdresIlceler]    Script Date: 29.01.2021 16:08:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AdresIlceler](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[SehirId] [int] NOT NULL,
	[Ad] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_dbo.AdresIlceler] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Adresler]    Script Date: 29.01.2021 16:08:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Adresler](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[IlceId] [int] NOT NULL,
	[AcikAdres] [nvarchar](500) NOT NULL,
 CONSTRAINT [PK_dbo.Adresler] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AdresSehirler]    Script Date: 29.01.2021 16:08:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AdresSehirler](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Ad] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_dbo.AdresSehirler] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BankaHesapHareketler]    Script Date: 29.01.2021 16:08:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BankaHesapHareketler](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[HesapId] [int] NOT NULL,
	[PersonelHarId] [int] NOT NULL,
	[CariHarId] [int] NOT NULL,
	[BelgeNo] [nvarchar](10) NOT NULL,
	[GirenMiktar] [money] NULL,
	[CikanMiktar] [money] NULL,
	[Tarih] [datetime] NOT NULL,
	[Aciklama] [nvarchar](max) NULL,
 CONSTRAINT [PK_dbo.BankaHesapHareketler] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BankaHesaplar]    Script Date: 29.01.2021 16:08:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BankaHesaplar](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[SubeId] [int] NOT NULL,
	[HesapNo] [nvarchar](50) NOT NULL,
	[Ad] [nvarchar](50) NOT NULL,
	[No] [nvarchar](50) NOT NULL,
	[IBAN] [nvarchar](50) NOT NULL,
	[MusteriYetkilisi] [nvarchar](50) NULL,
	[Aciklama] [nvarchar](max) NULL,
 CONSTRAINT [PK_dbo.BankaHesaplar] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Bankalar]    Script Date: 29.01.2021 16:08:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Bankalar](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Ad] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_dbo.Bankalar] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BankaSubeler]    Script Date: 29.01.2021 16:08:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BankaSubeler](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[BankaId] [int] NOT NULL,
	[Ad] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_dbo.BankaSubeler] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BorcCekler]    Script Date: 29.01.2021 16:08:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BorcCekler](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CekId] [int] NULL,
	[CariIdVerilen] [int] NOT NULL,
	[HesapId] [int] NOT NULL,
	[CikisTarihi] [datetime] NOT NULL,
 CONSTRAINT [PK_dbo.BorcCekler] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UK_BorcCekId] UNIQUE NONCLUSTERED 
(
	[CekId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BorcSenetler]    Script Date: 29.01.2021 16:08:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BorcSenetler](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[SenetId] [int] NULL,
	[CariIdVerilen] [int] NOT NULL,
	[CikisTarihi] [datetime] NOT NULL,
 CONSTRAINT [PK_dbo.BorcSenetler] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UK_BorcSenetId] UNIQUE NONCLUSTERED 
(
	[SenetId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CariGrupKodlar]    Script Date: 29.01.2021 16:08:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CariGrupKodlar](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Tur] [nvarchar](50) NOT NULL,
	[Ad] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_dbo.CariGrupKodlar] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CariGruplar]    Script Date: 29.01.2021 16:08:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CariGruplar](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CariId] [int] NULL,
	[CariGrupKodId] [int] NOT NULL,
 CONSTRAINT [PK_dbo.CariGruplar] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CariHareketler]    Script Date: 29.01.2021 16:08:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CariHareketler](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CariId] [int] NOT NULL,
	[Borc] [money] NOT NULL,
	[Alacak] [money] NOT NULL,
	[Tarih] [datetime] NOT NULL,
	[Aciklama] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_dbo.CariHareketler] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Cariler]    Script Date: 29.01.2021 16:08:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cariler](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Kod] [nvarchar](50) NOT NULL,
	[Unvan] [nvarchar](150) NOT NULL,
	[VergiDairesi] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Cariler] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UK_CariKod] UNIQUE NONCLUSTERED 
(
	[Kod] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Cekler]    Script Date: 29.01.2021 16:08:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cekler](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[DegerliEvrakId] [int] NULL,
	[BankaId] [int] NOT NULL,
	[Kod] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Cekler] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UK_BankaId] UNIQUE NONCLUSTERED 
(
	[BankaId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UK_CeklerDegerliEvrakId] UNIQUE NONCLUSTERED 
(
	[DegerliEvrakId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DegerliEvraklar]    Script Date: 29.01.2021 16:08:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DegerliEvraklar](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Vade] [datetime] NOT NULL,
	[Tutar] [money] NOT NULL,
	[Aciklama] [nvarchar](250) NULL,
 CONSTRAINT [PK_dbo.DegerliEvraklar] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Depolar]    Script Date: 29.01.2021 16:08:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Depolar](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[AdresId] [int] NOT NULL,
	[Ad] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_dbo.Depolar] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Evraklar]    Script Date: 29.01.2021 16:08:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Evraklar](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CariHarId] [int] NOT NULL,
	[PersonelHarId] [int] NOT NULL,
	[Tarih] [datetime] NOT NULL,
	[KayitTarihi] [datetime] NOT NULL,
	[Aciklama] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_dbo.Faturalar] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Faturalar]    Script Date: 29.01.2021 16:08:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Faturalar](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[EvrakId] [int] NOT NULL,
	[FaturaNo] [nvarchar](50) NOT NULL,
	[BrutTutar] [money] NOT NULL,
	[KDVlerToplam] [money] NOT NULL,
	[NetTutar] [money] NOT NULL,
 CONSTRAINT [PK_Faturalar] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UK_FaturaEvrakId] UNIQUE NONCLUSTERED 
(
	[EvrakId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Irsaliyeler]    Script Date: 29.01.2021 16:08:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Irsaliyeler](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[EvrakId] [int] NOT NULL,
	[IrsaliyeNo] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Irsaliyeler] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UK_IrsaliyeEvrakId] UNIQUE NONCLUSTERED 
(
	[EvrakId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[KasaHareketler]    Script Date: 29.01.2021 16:08:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KasaHareketler](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[KasaId] [int] NOT NULL,
	[PersonelHarId] [int] NULL,
	[CariHarId] [int] NULL,
	[BelgeNo] [nvarchar](20) NOT NULL,
	[GirenMiktar] [money] NULL,
	[CikanMiktar] [money] NULL,
	[Tarih] [datetime] NOT NULL,
	[Aciklama] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_dbo.KasaHareketler] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Kasalar]    Script Date: 29.01.2021 16:08:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Kasalar](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Ad] [nvarchar](50) NOT NULL,
	[Aciklama] [nvarchar](max) NULL,
 CONSTRAINT [PK_dbo.Kasalar] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Mailler]    Script Date: 29.01.2021 16:08:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Mailler](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Email] [nvarchar](75) NOT NULL,
 CONSTRAINT [PK_dbo.Mailler] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MusteriCekler]    Script Date: 29.01.2021 16:08:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MusteriCekler](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CekId] [int] NULL,
	[CariIdCiroEden] [int] NOT NULL,
	[CariIdCiroEdilen] [int] NULL,
	[HesapIdTahsileVerilen] [int] NULL,
	[AsilBorclu] [nvarchar](100) NOT NULL,
	[AlisTarihi] [datetime] NOT NULL,
	[CikisTarihi] [datetime] NULL,
 CONSTRAINT [PK_dbo.MusteriCekler] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UK_MusteriCekId] UNIQUE NONCLUSTERED 
(
	[CekId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MusteriSenetler]    Script Date: 29.01.2021 16:08:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MusteriSenetler](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[SenetId] [int] NULL,
	[CariIdCiroEden] [int] NOT NULL,
	[CariIdCiroEdilen] [int] NULL,
	[HesapIdTahsileVerilen] [int] NULL,
	[AsilBorclu] [nvarchar](50) NOT NULL,
	[AlisTarihi] [datetime] NOT NULL,
	[CikisTarihi] [datetime] NULL,
 CONSTRAINT [PK_dbo.MusteriSenetler] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UK_MusteriSenetId] UNIQUE NONCLUSTERED 
(
	[SenetId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PersonelHareketler]    Script Date: 29.01.2021 16:08:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PersonelHareketler](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[PersonelId] [int] NOT NULL,
	[TurId] [int] NOT NULL,
	[IslemTarihi] [datetime] NOT NULL,
 CONSTRAINT [PK_dbo.PersonelHareketler] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PersonelHareketTurler]    Script Date: 29.01.2021 16:08:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PersonelHareketTurler](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Ad] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_dbo.PersonelHareketTurler] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Personeller]    Script Date: 29.01.2021 16:08:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Personeller](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Ad] [nvarchar](50) NOT NULL,
	[IkinciAd] [nvarchar](10) NULL,
	[Soyad] [nvarchar](10) NOT NULL,
	[TCNo] [nvarchar](11) NOT NULL,
	[Cinsiyet] [nvarchar](5) NOT NULL,
	[MedeniHal] [nvarchar](20) NOT NULL,
	[CocukSayisi] [tinyint] NOT NULL,
	[DogumTarihi] [datetime] NOT NULL,
	[KatSayi] [decimal](18, 2) NOT NULL,
	[Birim] [nvarchar](50) NOT NULL,
	[Gorev] [nvarchar](50) NOT NULL,
	[Izin] [smallint] NOT NULL,
 CONSTRAINT [PK_dbo.Personeller] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SahisCariler]    Script Date: 29.01.2021 16:08:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SahisCariler](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CariId] [int] NOT NULL,
	[TCNo] [nvarchar](11) NOT NULL,
 CONSTRAINT [PK_dbo.SahisCariler] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UK_SahisCariId] UNIQUE NONCLUSTERED 
(
	[CariId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UK_TCNo] UNIQUE NONCLUSTERED 
(
	[TCNo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Senetler]    Script Date: 29.01.2021 16:08:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Senetler](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[DegerliEvrakId] [int] NULL,
	[Kod] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Senetler] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UK_SenetlerDegerliEvrakId] UNIQUE NONCLUSTERED 
(
	[DegerliEvrakId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SirketCariler]    Script Date: 29.01.2021 16:08:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SirketCariler](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CariId] [int] NOT NULL,
	[VergiNo] [nvarchar](10) NOT NULL,
 CONSTRAINT [PK_SirketCariler] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UK_SirketCariId] UNIQUE NONCLUSTERED 
(
	[CariId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UK_VergiNo] UNIQUE NONCLUSTERED 
(
	[VergiNo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[StokGrupKodlar]    Script Date: 29.01.2021 16:08:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[StokGrupKodlar](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Tur] [nvarchar](50) NOT NULL,
	[Ad] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_dbo.StokGrupKodlar] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[StokGruplar]    Script Date: 29.01.2021 16:08:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[StokGruplar](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[StokId] [int] NULL,
	[StokGrupKodId] [int] NOT NULL,
 CONSTRAINT [PK_dbo.StokGruplar] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[StokHareketler]    Script Date: 29.01.2021 16:08:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[StokHareketler](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[StokId] [int] NOT NULL,
	[EvrakId] [int] NOT NULL,
	[DepoId] [int] NOT NULL,
	[GirenMiktar] [decimal](18, 2) NOT NULL,
	[CikanMiktar] [decimal](18, 2) NOT NULL,
	[Birim] [nvarchar](50) NOT NULL,
	[Fiyat] [money] NULL,
	[KDV] [int] NULL,
	[BrutTutar] [money] NULL,
	[NetTutar] [money] NULL,
	[Tarih] [datetime] NOT NULL,
	[Aciklama] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_dbo.StokHareketler] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Stoklar]    Script Date: 29.01.2021 16:08:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Stoklar](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Kod] [nvarchar](50) NOT NULL,
	[Barkod] [nvarchar](50) NULL,
	[Ad] [nvarchar](50) NOT NULL,
	[KDV] [int] NULL,
	[Birim] [nvarchar](50) NULL,
	[Birim2] [nvarchar](50) NULL,
	[Birim2Oran] [float] NULL,
	[Birim3] [nvarchar](50) NULL,
	[Birim3Oran] [float] NULL,
 CONSTRAINT [PK_Stoklar] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UK_Barkod] UNIQUE NONCLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UK_StokKod] UNIQUE NONCLUSTERED 
(
	[Kod] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Telefonlar]    Script Date: 29.01.2021 16:08:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Telefonlar](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[No] [nvarchar](14) NOT NULL,
	[TelefonTipi] [nvarchar](50) NULL,
	[Aciklama] [nvarchar](75) NULL,
 CONSTRAINT [PK_dbo.Telefonlar] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Webler]    Script Date: 29.01.2021 16:08:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Webler](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[www] [nvarchar](250) NOT NULL,
 CONSTRAINT [PK_dbo.Webler] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [IX_SehirId]    Script Date: 29.01.2021 16:08:20 ******/
CREATE NONCLUSTERED INDEX [IX_SehirId] ON [dbo].[AdresIlceler]
(
	[SehirId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_IlceId]    Script Date: 29.01.2021 16:08:20 ******/
CREATE NONCLUSTERED INDEX [IX_IlceId] ON [dbo].[Adresler]
(
	[IlceId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_BelgeNo]    Script Date: 29.01.2021 16:08:20 ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_BelgeNo] ON [dbo].[BankaHesapHareketler]
(
	[BelgeNo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_CariHarId]    Script Date: 29.01.2021 16:08:20 ******/
CREATE NONCLUSTERED INDEX [IX_CariHarId] ON [dbo].[BankaHesapHareketler]
(
	[CariHarId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_HesapId]    Script Date: 29.01.2021 16:08:20 ******/
CREATE NONCLUSTERED INDEX [IX_HesapId] ON [dbo].[BankaHesapHareketler]
(
	[HesapId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_PersonelHarId]    Script Date: 29.01.2021 16:08:20 ******/
CREATE NONCLUSTERED INDEX [IX_PersonelHarId] ON [dbo].[BankaHesapHareketler]
(
	[PersonelHarId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_SubeId]    Script Date: 29.01.2021 16:08:20 ******/
CREATE NONCLUSTERED INDEX [IX_SubeId] ON [dbo].[BankaHesaplar]
(
	[SubeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_BankaId]    Script Date: 29.01.2021 16:08:20 ******/
CREATE NONCLUSTERED INDEX [IX_BankaId] ON [dbo].[BankaSubeler]
(
	[BankaId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Id]    Script Date: 29.01.2021 16:08:20 ******/
CREATE NONCLUSTERED INDEX [IX_Id] ON [dbo].[BankaSubeler]
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_CariIdVerilen]    Script Date: 29.01.2021 16:08:20 ******/
CREATE NONCLUSTERED INDEX [IX_CariIdVerilen] ON [dbo].[BorcCekler]
(
	[CariIdVerilen] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_HesapId]    Script Date: 29.01.2021 16:08:20 ******/
CREATE NONCLUSTERED INDEX [IX_HesapId] ON [dbo].[BorcCekler]
(
	[HesapId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_CariIdVerilen]    Script Date: 29.01.2021 16:08:20 ******/
CREATE NONCLUSTERED INDEX [IX_CariIdVerilen] ON [dbo].[BorcSenetler]
(
	[CariIdVerilen] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_CariId]    Script Date: 29.01.2021 16:08:20 ******/
CREATE NONCLUSTERED INDEX [IX_CariId] ON [dbo].[CariHareketler]
(
	[CariId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Id]    Script Date: 29.01.2021 16:08:20 ******/
CREATE NONCLUSTERED INDEX [IX_Id] ON [dbo].[Depolar]
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_CariHarId]    Script Date: 29.01.2021 16:08:20 ******/
CREATE NONCLUSTERED INDEX [IX_CariHarId] ON [dbo].[Evraklar]
(
	[CariHarId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_PersonelHarId]    Script Date: 29.01.2021 16:08:20 ******/
CREATE NONCLUSTERED INDEX [IX_PersonelHarId] ON [dbo].[Evraklar]
(
	[PersonelHarId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_BelgeNo]    Script Date: 29.01.2021 16:08:20 ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_BelgeNo] ON [dbo].[KasaHareketler]
(
	[BelgeNo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_CariHarId]    Script Date: 29.01.2021 16:08:20 ******/
CREATE NONCLUSTERED INDEX [IX_CariHarId] ON [dbo].[KasaHareketler]
(
	[CariHarId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_KasaId]    Script Date: 29.01.2021 16:08:20 ******/
CREATE NONCLUSTERED INDEX [IX_KasaId] ON [dbo].[KasaHareketler]
(
	[KasaId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_PersonelHarId]    Script Date: 29.01.2021 16:08:20 ******/
CREATE NONCLUSTERED INDEX [IX_PersonelHarId] ON [dbo].[KasaHareketler]
(
	[PersonelHarId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_Email]    Script Date: 29.01.2021 16:08:20 ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_Email] ON [dbo].[Mailler]
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_CariIdCiroEden]    Script Date: 29.01.2021 16:08:20 ******/
CREATE NONCLUSTERED INDEX [IX_CariIdCiroEden] ON [dbo].[MusteriCekler]
(
	[CariIdCiroEden] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_CariIdCiroEdilen]    Script Date: 29.01.2021 16:08:20 ******/
CREATE NONCLUSTERED INDEX [IX_CariIdCiroEdilen] ON [dbo].[MusteriCekler]
(
	[CariIdCiroEdilen] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_HesapIdTahsileVerilen]    Script Date: 29.01.2021 16:08:20 ******/
CREATE NONCLUSTERED INDEX [IX_HesapIdTahsileVerilen] ON [dbo].[MusteriCekler]
(
	[HesapIdTahsileVerilen] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_CariIdCiroEden]    Script Date: 29.01.2021 16:08:20 ******/
CREATE NONCLUSTERED INDEX [IX_CariIdCiroEden] ON [dbo].[MusteriSenetler]
(
	[CariIdCiroEden] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_CariIdCiroEdilen]    Script Date: 29.01.2021 16:08:20 ******/
CREATE NONCLUSTERED INDEX [IX_CariIdCiroEdilen] ON [dbo].[MusteriSenetler]
(
	[CariIdCiroEdilen] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_HesapIdTahsileVerilen]    Script Date: 29.01.2021 16:08:20 ******/
CREATE NONCLUSTERED INDEX [IX_HesapIdTahsileVerilen] ON [dbo].[MusteriSenetler]
(
	[HesapIdTahsileVerilen] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_PersonelId]    Script Date: 29.01.2021 16:08:20 ******/
CREATE NONCLUSTERED INDEX [IX_PersonelId] ON [dbo].[PersonelHareketler]
(
	[PersonelId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_TurId]    Script Date: 29.01.2021 16:08:20 ******/
CREATE NONCLUSTERED INDEX [IX_TurId] ON [dbo].[PersonelHareketler]
(
	[TurId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_TCNo]    Script Date: 29.01.2021 16:08:20 ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_TCNo] ON [dbo].[Personeller]
(
	[TCNo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_DepoId]    Script Date: 29.01.2021 16:08:20 ******/
CREATE NONCLUSTERED INDEX [IX_DepoId] ON [dbo].[StokHareketler]
(
	[DepoId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_FaturaId]    Script Date: 29.01.2021 16:08:20 ******/
CREATE NONCLUSTERED INDEX [IX_FaturaId] ON [dbo].[StokHareketler]
(
	[EvrakId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_StokId]    Script Date: 29.01.2021 16:08:20 ******/
CREATE NONCLUSTERED INDEX [IX_StokId] ON [dbo].[StokHareketler]
(
	[StokId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AdresIlceler]  WITH CHECK ADD  CONSTRAINT [FK_dbo.AdresIlceler_dbo.AdresSehirler_SehirId] FOREIGN KEY([SehirId])
REFERENCES [dbo].[AdresSehirler] ([Id])
GO
ALTER TABLE [dbo].[AdresIlceler] CHECK CONSTRAINT [FK_dbo.AdresIlceler_dbo.AdresSehirler_SehirId]
GO
ALTER TABLE [dbo].[Adresler]  WITH CHECK ADD  CONSTRAINT [FK_dbo.Adresler_dbo.AdresIlceler_IlceId] FOREIGN KEY([IlceId])
REFERENCES [dbo].[AdresIlceler] ([Id])
GO
ALTER TABLE [dbo].[Adresler] CHECK CONSTRAINT [FK_dbo.Adresler_dbo.AdresIlceler_IlceId]
GO
ALTER TABLE [dbo].[BankaHesapHareketler]  WITH CHECK ADD  CONSTRAINT [FK_dbo.BankaHesapHareketler_dbo.BankaHesaplar_HesapId] FOREIGN KEY([HesapId])
REFERENCES [dbo].[BankaHesaplar] ([Id])
GO
ALTER TABLE [dbo].[BankaHesapHareketler] CHECK CONSTRAINT [FK_dbo.BankaHesapHareketler_dbo.BankaHesaplar_HesapId]
GO
ALTER TABLE [dbo].[BankaHesapHareketler]  WITH CHECK ADD  CONSTRAINT [FK_dbo.BankaHesapHareketler_dbo.CariHareketler_CariHarId] FOREIGN KEY([CariHarId])
REFERENCES [dbo].[CariHareketler] ([Id])
GO
ALTER TABLE [dbo].[BankaHesapHareketler] CHECK CONSTRAINT [FK_dbo.BankaHesapHareketler_dbo.CariHareketler_CariHarId]
GO
ALTER TABLE [dbo].[BankaHesapHareketler]  WITH CHECK ADD  CONSTRAINT [FK_dbo.BankaHesapHareketler_dbo.Personeller_PersonelHarId] FOREIGN KEY([PersonelHarId])
REFERENCES [dbo].[Personeller] ([Id])
GO
ALTER TABLE [dbo].[BankaHesapHareketler] CHECK CONSTRAINT [FK_dbo.BankaHesapHareketler_dbo.Personeller_PersonelHarId]
GO
ALTER TABLE [dbo].[BankaHesaplar]  WITH CHECK ADD  CONSTRAINT [FK_dbo.BankaHesaplar_dbo.BankaSubeler_SubeId] FOREIGN KEY([SubeId])
REFERENCES [dbo].[BankaSubeler] ([Id])
GO
ALTER TABLE [dbo].[BankaHesaplar] CHECK CONSTRAINT [FK_dbo.BankaHesaplar_dbo.BankaSubeler_SubeId]
GO
ALTER TABLE [dbo].[BankaSubeler]  WITH CHECK ADD  CONSTRAINT [FK_dbo.BankaSubeler_dbo.Adresler_Id] FOREIGN KEY([Id])
REFERENCES [dbo].[Adresler] ([Id])
GO
ALTER TABLE [dbo].[BankaSubeler] CHECK CONSTRAINT [FK_dbo.BankaSubeler_dbo.Adresler_Id]
GO
ALTER TABLE [dbo].[BankaSubeler]  WITH CHECK ADD  CONSTRAINT [FK_dbo.BankaSubeler_dbo.Bankalar_BankaId] FOREIGN KEY([BankaId])
REFERENCES [dbo].[Bankalar] ([Id])
GO
ALTER TABLE [dbo].[BankaSubeler] CHECK CONSTRAINT [FK_dbo.BankaSubeler_dbo.Bankalar_BankaId]
GO
ALTER TABLE [dbo].[BorcCekler]  WITH CHECK ADD  CONSTRAINT [FK_BorcCekler_Cekler] FOREIGN KEY([CekId])
REFERENCES [dbo].[Cekler] ([DegerliEvrakId])
GO
ALTER TABLE [dbo].[BorcCekler] CHECK CONSTRAINT [FK_BorcCekler_Cekler]
GO
ALTER TABLE [dbo].[BorcCekler]  WITH CHECK ADD  CONSTRAINT [FK_dbo.BorcCekler_dbo.BankaHesaplar_HesapId] FOREIGN KEY([HesapId])
REFERENCES [dbo].[BankaHesaplar] ([Id])
GO
ALTER TABLE [dbo].[BorcCekler] CHECK CONSTRAINT [FK_dbo.BorcCekler_dbo.BankaHesaplar_HesapId]
GO
ALTER TABLE [dbo].[BorcCekler]  WITH CHECK ADD  CONSTRAINT [FK_dbo.BorcCekler_dbo.Cariler_CariIdVerilen] FOREIGN KEY([CariIdVerilen])
REFERENCES [dbo].[Cariler] ([Id])
GO
ALTER TABLE [dbo].[BorcCekler] CHECK CONSTRAINT [FK_dbo.BorcCekler_dbo.Cariler_CariIdVerilen]
GO
ALTER TABLE [dbo].[BorcSenetler]  WITH CHECK ADD  CONSTRAINT [FK_dbo.BorcSenetler_dbo.Cariler_CariIdVerilen] FOREIGN KEY([CariIdVerilen])
REFERENCES [dbo].[Cariler] ([Id])
GO
ALTER TABLE [dbo].[BorcSenetler] CHECK CONSTRAINT [FK_dbo.BorcSenetler_dbo.Cariler_CariIdVerilen]
GO
ALTER TABLE [dbo].[BorcSenetler]  WITH CHECK ADD  CONSTRAINT [FK_dbo.BorcSenetler_dbo.Senetler_Id] FOREIGN KEY([Id])
REFERENCES [dbo].[Senetler] ([Id])
GO
ALTER TABLE [dbo].[BorcSenetler] CHECK CONSTRAINT [FK_dbo.BorcSenetler_dbo.Senetler_Id]
GO
ALTER TABLE [dbo].[CariGruplar]  WITH CHECK ADD  CONSTRAINT [FK_dbo.CariGruplar_dbo.CariGrupKodlar_CariGrupKodId] FOREIGN KEY([CariGrupKodId])
REFERENCES [dbo].[CariGrupKodlar] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[CariGruplar] CHECK CONSTRAINT [FK_dbo.CariGruplar_dbo.CariGrupKodlar_CariGrupKodId]
GO
ALTER TABLE [dbo].[CariGruplar]  WITH CHECK ADD  CONSTRAINT [FK_dbo.CariGruplar_dbo.Cariler_CariId] FOREIGN KEY([CariId])
REFERENCES [dbo].[Cariler] ([Id])
GO
ALTER TABLE [dbo].[CariGruplar] CHECK CONSTRAINT [FK_dbo.CariGruplar_dbo.Cariler_CariId]
GO
ALTER TABLE [dbo].[CariHareketler]  WITH CHECK ADD  CONSTRAINT [FK_dbo.CariHareketler_dbo.Cariler_CariId] FOREIGN KEY([CariId])
REFERENCES [dbo].[Cariler] ([Id])
GO
ALTER TABLE [dbo].[CariHareketler] CHECK CONSTRAINT [FK_dbo.CariHareketler_dbo.Cariler_CariId]
GO
ALTER TABLE [dbo].[Cekler]  WITH CHECK ADD  CONSTRAINT [FK_Cekler_DegerliEvraklar] FOREIGN KEY([DegerliEvrakId])
REFERENCES [dbo].[DegerliEvraklar] ([Id])
GO
ALTER TABLE [dbo].[Cekler] CHECK CONSTRAINT [FK_Cekler_DegerliEvraklar]
GO
ALTER TABLE [dbo].[Cekler]  WITH CHECK ADD  CONSTRAINT [FK_dbo.Cekler_dbo.Bankalar_BankaId] FOREIGN KEY([BankaId])
REFERENCES [dbo].[Bankalar] ([Id])
GO
ALTER TABLE [dbo].[Cekler] CHECK CONSTRAINT [FK_dbo.Cekler_dbo.Bankalar_BankaId]
GO
ALTER TABLE [dbo].[Depolar]  WITH CHECK ADD  CONSTRAINT [FK_dbo.Depolar_dbo.Adresler_Id] FOREIGN KEY([Id])
REFERENCES [dbo].[Adresler] ([Id])
GO
ALTER TABLE [dbo].[Depolar] CHECK CONSTRAINT [FK_dbo.Depolar_dbo.Adresler_Id]
GO
ALTER TABLE [dbo].[Evraklar]  WITH CHECK ADD  CONSTRAINT [FK_dbo.Faturalar_dbo.CariHareketler_CariHarId] FOREIGN KEY([CariHarId])
REFERENCES [dbo].[CariHareketler] ([Id])
GO
ALTER TABLE [dbo].[Evraklar] CHECK CONSTRAINT [FK_dbo.Faturalar_dbo.CariHareketler_CariHarId]
GO
ALTER TABLE [dbo].[Evraklar]  WITH CHECK ADD  CONSTRAINT [FK_dbo.Faturalar_dbo.PersonelHareketler_PersonelHarId] FOREIGN KEY([PersonelHarId])
REFERENCES [dbo].[PersonelHareketler] ([Id])
GO
ALTER TABLE [dbo].[Evraklar] CHECK CONSTRAINT [FK_dbo.Faturalar_dbo.PersonelHareketler_PersonelHarId]
GO
ALTER TABLE [dbo].[Faturalar]  WITH CHECK ADD  CONSTRAINT [FK_Faturalar_Evraklar] FOREIGN KEY([EvrakId])
REFERENCES [dbo].[Evraklar] ([Id])
GO
ALTER TABLE [dbo].[Faturalar] CHECK CONSTRAINT [FK_Faturalar_Evraklar]
GO
ALTER TABLE [dbo].[Irsaliyeler]  WITH CHECK ADD  CONSTRAINT [FK_Irsaliyeler_Evraklar] FOREIGN KEY([EvrakId])
REFERENCES [dbo].[Evraklar] ([Id])
GO
ALTER TABLE [dbo].[Irsaliyeler] CHECK CONSTRAINT [FK_Irsaliyeler_Evraklar]
GO
ALTER TABLE [dbo].[KasaHareketler]  WITH CHECK ADD  CONSTRAINT [FK_dbo.KasaHareketler_dbo.CariHareketler_CariHarId] FOREIGN KEY([CariHarId])
REFERENCES [dbo].[CariHareketler] ([Id])
GO
ALTER TABLE [dbo].[KasaHareketler] CHECK CONSTRAINT [FK_dbo.KasaHareketler_dbo.CariHareketler_CariHarId]
GO
ALTER TABLE [dbo].[KasaHareketler]  WITH CHECK ADD  CONSTRAINT [FK_dbo.KasaHareketler_dbo.Kasalar_KasaId] FOREIGN KEY([KasaId])
REFERENCES [dbo].[Kasalar] ([Id])
GO
ALTER TABLE [dbo].[KasaHareketler] CHECK CONSTRAINT [FK_dbo.KasaHareketler_dbo.Kasalar_KasaId]
GO
ALTER TABLE [dbo].[KasaHareketler]  WITH CHECK ADD  CONSTRAINT [FK_dbo.KasaHareketler_dbo.PersonelHareketler_PersonelHarId] FOREIGN KEY([PersonelHarId])
REFERENCES [dbo].[PersonelHareketler] ([Id])
GO
ALTER TABLE [dbo].[KasaHareketler] CHECK CONSTRAINT [FK_dbo.KasaHareketler_dbo.PersonelHareketler_PersonelHarId]
GO
ALTER TABLE [dbo].[MusteriCekler]  WITH CHECK ADD  CONSTRAINT [FK_dbo.MusteriCekler_dbo.BankaHesaplar_HesapIdTahsileVerilen] FOREIGN KEY([HesapIdTahsileVerilen])
REFERENCES [dbo].[BankaHesaplar] ([Id])
GO
ALTER TABLE [dbo].[MusteriCekler] CHECK CONSTRAINT [FK_dbo.MusteriCekler_dbo.BankaHesaplar_HesapIdTahsileVerilen]
GO
ALTER TABLE [dbo].[MusteriCekler]  WITH CHECK ADD  CONSTRAINT [FK_dbo.MusteriCekler_dbo.Cariler_CariIdCiroEden] FOREIGN KEY([CariIdCiroEden])
REFERENCES [dbo].[Cariler] ([Id])
GO
ALTER TABLE [dbo].[MusteriCekler] CHECK CONSTRAINT [FK_dbo.MusteriCekler_dbo.Cariler_CariIdCiroEden]
GO
ALTER TABLE [dbo].[MusteriCekler]  WITH CHECK ADD  CONSTRAINT [FK_dbo.MusteriCekler_dbo.Cariler_CariIdCiroEdilen] FOREIGN KEY([CariIdCiroEdilen])
REFERENCES [dbo].[Cariler] ([Id])
GO
ALTER TABLE [dbo].[MusteriCekler] CHECK CONSTRAINT [FK_dbo.MusteriCekler_dbo.Cariler_CariIdCiroEdilen]
GO
ALTER TABLE [dbo].[MusteriCekler]  WITH CHECK ADD  CONSTRAINT [FK_MusteriCekler_Cekler] FOREIGN KEY([CekId])
REFERENCES [dbo].[Cekler] ([DegerliEvrakId])
GO
ALTER TABLE [dbo].[MusteriCekler] CHECK CONSTRAINT [FK_MusteriCekler_Cekler]
GO
ALTER TABLE [dbo].[MusteriSenetler]  WITH CHECK ADD  CONSTRAINT [FK_dbo.MusteriSenetler_dbo.BankaHesaplar_HesapIdTahsileVerilen] FOREIGN KEY([HesapIdTahsileVerilen])
REFERENCES [dbo].[BankaHesaplar] ([Id])
GO
ALTER TABLE [dbo].[MusteriSenetler] CHECK CONSTRAINT [FK_dbo.MusteriSenetler_dbo.BankaHesaplar_HesapIdTahsileVerilen]
GO
ALTER TABLE [dbo].[MusteriSenetler]  WITH CHECK ADD  CONSTRAINT [FK_dbo.MusteriSenetler_dbo.Cariler_CariIdCiroEden] FOREIGN KEY([CariIdCiroEden])
REFERENCES [dbo].[Cariler] ([Id])
GO
ALTER TABLE [dbo].[MusteriSenetler] CHECK CONSTRAINT [FK_dbo.MusteriSenetler_dbo.Cariler_CariIdCiroEden]
GO
ALTER TABLE [dbo].[MusteriSenetler]  WITH CHECK ADD  CONSTRAINT [FK_dbo.MusteriSenetler_dbo.Cariler_CariIdCiroEdilen] FOREIGN KEY([CariIdCiroEdilen])
REFERENCES [dbo].[Cariler] ([Id])
GO
ALTER TABLE [dbo].[MusteriSenetler] CHECK CONSTRAINT [FK_dbo.MusteriSenetler_dbo.Cariler_CariIdCiroEdilen]
GO
ALTER TABLE [dbo].[MusteriSenetler]  WITH CHECK ADD  CONSTRAINT [FK_MusteriSenetler_Senetler] FOREIGN KEY([SenetId])
REFERENCES [dbo].[Senetler] ([DegerliEvrakId])
GO
ALTER TABLE [dbo].[MusteriSenetler] CHECK CONSTRAINT [FK_MusteriSenetler_Senetler]
GO
ALTER TABLE [dbo].[PersonelHareketler]  WITH CHECK ADD  CONSTRAINT [FK_dbo.PersonelHareketler_dbo.PersonelHareketTurler_TurId] FOREIGN KEY([TurId])
REFERENCES [dbo].[PersonelHareketTurler] ([Id])
GO
ALTER TABLE [dbo].[PersonelHareketler] CHECK CONSTRAINT [FK_dbo.PersonelHareketler_dbo.PersonelHareketTurler_TurId]
GO
ALTER TABLE [dbo].[PersonelHareketler]  WITH CHECK ADD  CONSTRAINT [FK_dbo.PersonelHareketler_dbo.Personeller_PersonelId] FOREIGN KEY([PersonelId])
REFERENCES [dbo].[Personeller] ([Id])
GO
ALTER TABLE [dbo].[PersonelHareketler] CHECK CONSTRAINT [FK_dbo.PersonelHareketler_dbo.Personeller_PersonelId]
GO
ALTER TABLE [dbo].[SahisCariler]  WITH CHECK ADD  CONSTRAINT [FK_SahisCariler_Cariler] FOREIGN KEY([CariId])
REFERENCES [dbo].[Cariler] ([Id])
GO
ALTER TABLE [dbo].[SahisCariler] CHECK CONSTRAINT [FK_SahisCariler_Cariler]
GO
ALTER TABLE [dbo].[Senetler]  WITH CHECK ADD  CONSTRAINT [FK_Senetler_DegerliEvraklar] FOREIGN KEY([DegerliEvrakId])
REFERENCES [dbo].[DegerliEvraklar] ([Id])
GO
ALTER TABLE [dbo].[Senetler] CHECK CONSTRAINT [FK_Senetler_DegerliEvraklar]
GO
ALTER TABLE [dbo].[SirketCariler]  WITH CHECK ADD  CONSTRAINT [FK_SirketCariler_Cariler] FOREIGN KEY([CariId])
REFERENCES [dbo].[Cariler] ([Id])
GO
ALTER TABLE [dbo].[SirketCariler] CHECK CONSTRAINT [FK_SirketCariler_Cariler]
GO
ALTER TABLE [dbo].[StokGruplar]  WITH CHECK ADD  CONSTRAINT [FK_dbo.StokGruplar_dbo.StokGrupKodlar_StokGrupKodId] FOREIGN KEY([StokGrupKodId])
REFERENCES [dbo].[StokGrupKodlar] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[StokGruplar] CHECK CONSTRAINT [FK_dbo.StokGruplar_dbo.StokGrupKodlar_StokGrupKodId]
GO
ALTER TABLE [dbo].[StokGruplar]  WITH CHECK ADD  CONSTRAINT [FK_StokGruplar_Stoklar] FOREIGN KEY([StokId])
REFERENCES [dbo].[Stoklar] ([Id])
GO
ALTER TABLE [dbo].[StokGruplar] CHECK CONSTRAINT [FK_StokGruplar_Stoklar]
GO
ALTER TABLE [dbo].[StokHareketler]  WITH CHECK ADD  CONSTRAINT [FK_dbo.StokHareketler_dbo.Depolar_DepoId] FOREIGN KEY([DepoId])
REFERENCES [dbo].[Depolar] ([Id])
GO
ALTER TABLE [dbo].[StokHareketler] CHECK CONSTRAINT [FK_dbo.StokHareketler_dbo.Depolar_DepoId]
GO
ALTER TABLE [dbo].[StokHareketler]  WITH CHECK ADD  CONSTRAINT [FK_dbo.StokHareketler_dbo.Evraklar_EvrakId] FOREIGN KEY([EvrakId])
REFERENCES [dbo].[Evraklar] ([Id])
GO
ALTER TABLE [dbo].[StokHareketler] CHECK CONSTRAINT [FK_dbo.StokHareketler_dbo.Evraklar_EvrakId]
GO
ALTER TABLE [dbo].[StokHareketler]  WITH CHECK ADD  CONSTRAINT [FK_dbo.StokHareketler_dbo.Stoklar_StokId] FOREIGN KEY([StokId])
REFERENCES [dbo].[Stoklar] ([Id])
GO
ALTER TABLE [dbo].[StokHareketler] CHECK CONSTRAINT [FK_dbo.StokHareketler_dbo.Stoklar_StokId]
GO
USE [master]
GO
ALTER DATABASE [OnMuhasebe] SET  READ_WRITE 
GO
